### PR TITLE
Updated Whitelist

### PR DESCRIPTION
**Pull request by Farioto**
Just Wondering Is This Okay? if not, sorry. :(

Added "intel" "Intel" "nvidia" "Nvidia" "Twitch"

### CODE REVIEW

**Comment by osxnick** [comment]
They should be okay, I'm sure Chan will merge this.

**Comment by Farioto** [comment]
i'd love to help any way I can, I used to play Toontown Online before it closed way back...

**Comment by chandler14362** [comment]
Just an FYI whoever wants to add words to whitelist: You don't need to add the uppercase version of the word! Its not required!

**Comment by Farioto** [comment]
Ah, Sorry About That. I wasn't too sure. Can I fix that and remove any of the existing words that have an extra uppercase copy? While adding some other words? That Okay? I Just want to help make the in-game chat more convenient than it already is. meaning adding words that should have existed anyways, and if its okay Some with lesser meanings like Company, Movie, Show, Video Game or Event words/names.

**Comment by chandler14362** [comment]
Its fine, im going to write a tool that will just remove all of the uppercase words.

**Comment by Farioto** [comment]
I already got 40 different words that should be acceptable. i'm done with them.

I noticed there are some duplicates of lowercase words too besides the the many uppercase ones.

and one question do I need to make changes in the edit window or can I copy it to notepad++ and edit there? because I'm using the web editor and it takes like 3 min just to add/remove when editing. Just asking because I can get all the Extra uppercase ones gone in an hour or 3 in notepad++.

**Pull request merged**
