### PR TITLE
Total Whitelist Update

### PR DESCRIPTION
**Pull request by Farioto**
Added: https://dl.dropboxusercontent.com/u/41141137/twhitelist/added.txt +241
Removed: https://dl.dropboxusercontent.com/u/41141137/twhitelist/removed.txt -9364

The list of Added And Removed Words was too long
So I Dropbox-ed the links to the whole lists.
It took me 6+ Hours.
I never removed any words that weren't a duplicate and i checked the list throughout the whole entire time.
I added any word that may have been missing or didn't have a lower case version of.
I hope this makes things easier. :D

Sorry If It doesn't show changes, reason why is because I had to mass cut one by one every duplicate and I couldn't do it in the github editor, it slowed my computer down between every cut so I had to use notepad++ and copy/paste everything back, and I must add, Every Word That Was Removed or Added were all cut and pasted, I Never deleted a word.

### CODE REVIEW

**Comment by enigmeow** [comment]
reviewing now...

**Comment by enigmeow** [comment]
Following words were missing.. Could you add them back in?
- alrighty
- america
- braken
- c#
- cataloging
- cataloguing
- cs
- cscript
- ddos
- ddosed
- ddosing
- dmg
- ebbohknee
- empower
- empowered
- empowering
- enigmeow
- exemplary
- fig
- friended
- gr8
- herro
- ily
- implode
- imploded
- imploding
- intel
- java
- javascript
- js
- ka
- kenneth
- l8r
- lego
- lel
- lul
- microsoft
- migos
- mishaps
- monodevelop
- notepad++
- nvidia
- obs
- offset
- orb
- orbs
- prower
- rosie
- saint
- saints
- satisfactory
- shutdown
- slick
- spiderman
- superman
- theta
- thrones
- tothestars
- tragedy
- triforce
- tru
- ttfs
- venom
- venomous
- visual
- visualization
- visualize
- xavier
- y'all
- yasss
- yess
- yesss
- yey
- yoshi
- zelda

**Comment by Farioto** [comment]
Ok, I Just Checked It https://github.com/labtech9999/resources/blob/patch-3/phase_4/etc/twhitelist.dat 
all of those words are in there, there was actually one extra lel I forgot to remove. and tru needed to be moved to the right spot and thats it, I Ctrl+F found all of them.

**Comment by chandler14362** [comment]
Ill make a tool to read your added.txt and put it inside the whitelist. Soon we will be moving the whitelist inside of the source so make sure to keep an eye out for that.

Thanks for all the words :+1:

**Pull request closed without merging**
